services:
  gobl-html:
    build:
      context: .
      dockerfile: Dockerfile.build
    ports:
      - "3000:3000"
    depends_on:
      - gotenberg
    environment:
      - PDF_URL=http://gotenberg:3000
    command: ["serve", "--pdf", "gotenberg", "--pdf-url", "http://gotenberg:3000"]

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3001:3000"
